	<?php
$countryCode = array('France'
		,'Afghanistan' 
		,'Afrique du Sud' 
		,'Aland' 
		,'Albanie' 
		,'Algérie' 
		,'Allemagne' 
		,'Andorre' 
		,'Angola' 
		,'Anguilla' 
		, 'Antarctique' 
		,'Antigua-et-Barbuda' 
		, 'Arabie saoudite' 
		,'Argentine' 
		,'Arménie' 
		, 'Aruba' 
		,'Australie' 
		,'Autriche' 
		,'Azerbaïdjan' 
		, 'Bahamas' 
		,'Bahreïn' 
		, 'Bangladesh' 
		,'Barbade' 
		,'Biélorussie' 
		,'Belgique' 
		, 'Belize' 
		, 'Bénin' 
		, 'Bermudes' 
		,'Bhoutan' 
		,'Bolivie' 
		,' St-Eustache et Saba' 
		,'Bosnie - Herzégovine' 
		,'Botswana' 
		, 'Île Bouvet' 
		, 'Brésil' 
		,'Brunei' 
		, 'Bulgarie' 
		,'Burkina Faso' 
		,'Burundi' 
		, 'Îles Caïmans' 
		,'Cambodge' 
		,'Cameroun' 
		,'Canada' 
		, 'Cap-Vert' 
		,'Centrafrique' 
		, 'Chili' 
		, 'Chine' 
		, 'Île Christmas' 
		,'Chypre' 
		,'Îles Cocos' 
		,'Colombie' 
		, 'Comores' 
		, 'République' 
		, 'RD Congo' 
		, 'Îles Cook' 
		, 'Corée du Sud' 
		,'Corée du Nord' 
		,'Costa Rica' 
		, 'Côte d\'Ivoire' 
		,'Croatie' 
		, 'Cuba' 
		, 'Curaçao' 
		, 'Danemark' 
		, 'Djibouti' 
		, 'Rép. dominicaine' 
		, 'Dominique' 
		,'Égypte' 
		, 'Salvador' 
		, 'Émirats arabes unis' 
		,'Équateur' 
		,'Érythrée' 
		, 'Espagne' 
		,'Estonie' 
		, 'États-Unis' 
		,'Éthiopie' 
		, 'Îles Malouines' 
		, 'Îles Féroé' 
		, 'Fidji' 
		, 'Finlande'
		, 'Gabon' 
		, 'Gambie' 
		, 'Géorgie' 
		,'Îles Sandwich du Sud' 
		,'Ghana' 
		,'Gibraltar' 
		,'Grèce' 
		, 'Grenade' 
		,'Groenland' 
		, 'Guadeloupe' 
		,'Guam' 
		,'Guatemala' 
		, 'Guernesey' 
		, 'Guinée' 
		, 'Guinée-Bissau' 
		, 'Guinée équatoriale' 
		,'Guyana' 
		, 'Guyane' 
		, 'Haïti'
		,'Honduras' 
		,'Hong Kong' 
		,'Hongrie' 
		, 'Île de Man' 
		,'Îles Vierges' 
		, 'Inde' 
		,'Indonésie' 
		, 'Iran' 
		, 'Irak' 
		, 'Irlande' 
		,'Islande' 
		,'Israël' 
		, 'Italie' 
		, 'Jamaïque' 
		,'Japon' 
		, 'Jersey' 
		, 'Jordanie' 
		, 'Kazakhstan' 
		,'Kenya' 
		, 'Kirghizistan' 
		,'Kiribati' 
		,'Koweït' 
		,'Laos' 
		,'Lesotho' 
		,'Lettonie' 
		,'Liban' 
		, 'Liberia' 
		,'Libye' 
		,'Liechtenstein' 
		,'Lituanie' 
		, 'Luxembourg' 
		,'Macao' 
		,'Macédoine' 
		,'Madagascar' 
		,'Malaisie' 
		,'Malawi' 
		,'Maldives' 
		,'Mali' 
		,'Malte' 
		,'Îles Mariannes' 
		,'Maroc' 
		,'Marshall' 
		,'Martinique' 
		, 'Maurice' 
		,'Mauritanie' 
		,'1Mayotte' 
		,'Mexique' 
		, 'Micronésie' 
		,'Moldavie' 
		,'Monaco' 
		, 'Mongolie' 
		,'Monténégro' 
		,'Montserrat' 
		,'Mozambique' 
		,'Birmanie' 
		,'Namibie' 
		,'Nauru' 
		,'Népal' 
		, 'Nicaragua' 
		, 'Niger' 
		, 'Nigeria' 
		,'Niue' 
		, 'Île Norfolk' 
		,'Norvège' 
		, 'Nouvelle-Calédonie' 
		, 'Nouvelle-Zélande'
		,'Oman' 
		,'Ouganda' 
		, 'Ouzbékistan' 
		, 'Pakistan' 
		, 'Palaos' 
		,'Autorité Palestinienne' 
		,'Panama' 
		,'Papouasie-N-Guinée' 
		,'Paraguay' 
		,'Pays-Bas' 
		,'Pérou' 
		,'Philippines' 
		, 'Îles Pitcairn' 
		,'Pologne' 
		, 'Polynésie française' 
		,'Porto Rico' 
		,'Portugal' 
		,'Qatar' 
		,'La Réunion' 
		,'Roumanie' 
		,'Royaume-Uni' 
		, 'Russie' 
		,'Rwanda' 
		,'Sahara  occidental' 
		, 'St-Barthélemy' 
		, 'St-Christophe' 
		, 'St-Marin' 
		,'St-Martin' 
		, 'St-Pierre -et- Miquelon ' 
		, 'Saint-Siège' 
		,'St-Vincent' 
		,'Ste-Hélène'
		,' Ascension' 
		, 'Ste-Lucie' 
		,'Salomon' 
		,'Samoa' 
		,'Samoa américaines' 
		, 'Sao Tomé -et-Principe' 
		,'Sénégal' 
		, 'Serbie' 
		,'Seychelles' 
		, 'Sierra Leone' 
		, 'Singapour' 
		,'Slovaquie' 
		,'Slovénie' 
		,'Somalie' 
		,'Soudan' 
		,'Soudan du Sud' 
		,'Sri Lanka' 
		,'Suède' 
		, 'Suisse' 
		,'Suriname' 
		,'Svalbard' 
		,'Swaziland' 
		,'Syrie' 
		, 'Tadjikistan' 
		, 'Taïwan' 
		,'Tanzanie' 
		, 'Tchad' 
		, 'République tchèque'
		,'Thaïlande' 
		,'Timor oriental' 
		,'Togo' 
		, 'Tokelau' 
		, 'Tonga' 
		, 'Trinité-et-Tobago' 
		,'Tunisie' 
		,'Turkménistan' 
		,'Turques-et-Caïques' 
		,'Turquie' 
		,'Tuvalu' 
		, 'Ukraine' 
		,'Uruguay' 
		, 'Vanuatu' 
		, 'Venezuela' 
		,'Viêt Nam' 
		,'Wallis-et-Futuna' 
		,'Yémen' 
		,'Zambie' 
		,'Zimbabwe'
		);

		foreach($countryCode as $key => $tab)
		{
			
				echo '<option value="'. $tab.'">'. $tab .'</option>';
	
			
		}
	?>